### ISSUE TITLE
Add second docker-compose file that adds support for portainers environment variables

### ISSUE THREAD

**Issue by speedfreakw** [fabianbees/breitbandmessung-docker#1]
It would be nice to have a second docker-compose file (eg. docker-compose-portainer.yml) that adds support for Portainer's stack environment variables feature. So you could deploy a Stack (Portainer's own Docker-Compose variation) directly from your repository via Portainer and define the port, the container name and the data path yourself according to your own system needs.

The compose file would look something like this:

```
version: '3.8'
services:
  breitband-desktop:
    image: breitband:latest
    build: .
    container_name: ${container-name}
    ports:
      - "${port}:5800"
    volumes:
      - "${data-path}:/config/xdg/config/Breitbandmessung"
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
```
