### ISSUE TITLE
Allow alternate VNC port

### ISSUE THREAD

**Issue by r0ckarong** [fabianbees/breitbandmessung-docker#18]
I'm trying to use the container but the ports 5800/5900 are already taken by another application on my setup. I changed the docker-compose file but it seems like the internal nginx is still using 5800 by default. Is there a way to simply change this via environment variable? I don't really want to shut down the other service just because the port collides.

Also I get a lot of seemingly GL / gfx related error messages. Is this because of the collision or something else?
I'm running on a Synology NAS from the docker-compose.yml file.

Here's the container log. When I try to connect to my custom port 5807 it says "The connection was reset".

I'm willing to reconfigure nginx when the container is running but I'm not sure what to do.

[breitband-desktop.csv](https://github.com/fabianbees/breitbandmessung-docker/files/13678335/breitband-desktop.csv)

**Comment by LizenzFass78851** [comment]
Did you really change the compose file like this?

```diff
version: "3.8"
services:
  breitband-desktop:
    image: fabianbees/breitbandmessung:latest
    container_name: breitband-desktop
    environment:
      - TZ=Europe/Berlin
    volumes:
      - $PWD/breitbandmessung/data:/config/xdg/config/Breitbandmessung
    ports:
-     - 5800:5800
+     - 5807:5800
    restart: unless-stopped 
```

**Comment by kaerbr** [comment]
You can just use another portmapping:

```yaml
version: "3.8"
services:
  breitband-desktop:
    image: fabianbees/breitbandmessung:latest
    container_name: breitband-desktop
    environment:
      - TZ=Europe/Berlin
    volumes:
      - $PWD/breitbandmessung/data:/config/xdg/config/Breitbandmessung
    ports:
      - 6000:5800
    restart: unless-stopped
```

With this config you should be able to access it via `localhost:6000`. The port will be mapped/routed to the port 5800 of the app.
